[2025-09-23T21:46:39.671-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-23T21:46:39.690-0300] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: WorkOrders.run_main scheduled__2025-09-23T11:00:00+00:00 [queued]>
[2025-09-23T21:46:39.696-0300] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: WorkOrders.run_main scheduled__2025-09-23T11:00:00+00:00 [queued]>
[2025-09-23T21:46:39.697-0300] {taskinstance.py:2884} INFO - Starting attempt 1 of 1
[2025-09-23T21:46:39.720-0300] {taskinstance.py:2907} INFO - Executing <Task(_PythonDecoratedOperator): run_main> on 2025-09-23 11:00:00+00:00
[2025-09-23T21:46:39.729-0300] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=146) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-23T21:46:39.731-0300] {standard_task_runner.py:72} INFO - Started process 148 to run task
[2025-09-23T21:46:39.731-0300] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'WorkOrders', 'run_main', 'scheduled__2025-09-23T11:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/Example.py', '--cfg-path', '/tmp/tmp8kkqgil4']
[2025-09-23T21:46:39.734-0300] {standard_task_runner.py:105} INFO - Job 10: Subtask run_main
[2025-09-23T21:46:39.796-0300] {task_command.py:467} INFO - Running <TaskInstance: WorkOrders.run_main scheduled__2025-09-23T11:00:00+00:00 [running]> on host 41dd0c7ecc28
[2025-09-23T21:46:39.885-0300] {taskinstance.py:3157} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='WorkOrders' AIRFLOW_CTX_TASK_ID='run_main' AIRFLOW_CTX_EXECUTION_DATE='2025-09-23T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-23T11:00:00+00:00'
[2025-09-23T21:46:39.886-0300] {taskinstance.py:740} INFO - ::endgroup::
[2025-09-23T21:46:43.907-0300] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2025-09-23T21:46:45.584-0300] {logging_mixin.py:190} INFO - 0 novas linhas para inserir.
[2025-09-23T21:46:45.584-0300] {logging_mixin.py:190} INFO - Nada a inserir. Encerrando.
[2025-09-23T21:46:45.585-0300] {python.py:240} INFO - Done. Returned value was: None
[2025-09-23T21:46:45.595-0300] {taskinstance.py:349} INFO - ::group::Post task execution logs
[2025-09-23T21:46:45.596-0300] {taskinstance.py:361} INFO - Marking task as SUCCESS. dag_id=WorkOrders, task_id=run_main, run_id=scheduled__2025-09-23T11:00:00+00:00, execution_date=20250923T110000, start_date=20250924T004639, end_date=20250924T004645
[2025-09-23T21:46:45.646-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-09-23T21:46:45.659-0300] {taskinstance.py:3924} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-23T21:46:45.661-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-09-23T21:52:09.492-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-23T21:52:09.511-0300] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: WorkOrders.run_main scheduled__2025-09-23T11:00:00+00:00 [queued]>
[2025-09-23T21:52:09.517-0300] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: WorkOrders.run_main scheduled__2025-09-23T11:00:00+00:00 [queued]>
[2025-09-23T21:52:09.517-0300] {taskinstance.py:2884} INFO - Starting attempt 1 of 1
[2025-09-23T21:52:09.545-0300] {taskinstance.py:2907} INFO - Executing <Task(_PythonDecoratedOperator): run_main> on 2025-09-23 11:00:00+00:00
[2025-09-23T21:52:09.554-0300] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=82) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-23T21:52:09.556-0300] {standard_task_runner.py:72} INFO - Started process 84 to run task
[2025-09-23T21:52:09.556-0300] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'WorkOrders', 'run_main', 'scheduled__2025-09-23T11:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/Example.py', '--cfg-path', '/tmp/tmpqhihox1f']
[2025-09-23T21:52:09.558-0300] {standard_task_runner.py:105} INFO - Job 15: Subtask run_main
[2025-09-23T21:52:09.619-0300] {task_command.py:467} INFO - Running <TaskInstance: WorkOrders.run_main scheduled__2025-09-23T11:00:00+00:00 [running]> on host 29b76035fcd4
[2025-09-23T21:52:09.695-0300] {taskinstance.py:3157} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='WorkOrders' AIRFLOW_CTX_TASK_ID='run_main' AIRFLOW_CTX_EXECUTION_DATE='2025-09-23T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-23T11:00:00+00:00'
[2025-09-23T21:52:09.696-0300] {taskinstance.py:740} INFO - ::endgroup::
[2025-09-23T21:52:13.020-0300] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2025-09-23T21:52:13.786-0300] {logging_mixin.py:190} INFO - 0 novas linhas para inserir.
[2025-09-23T21:52:13.786-0300] {logging_mixin.py:190} INFO - Nada a inserir. Encerrando.
[2025-09-23T21:52:13.787-0300] {python.py:240} INFO - Done. Returned value was: None
[2025-09-23T21:52:13.797-0300] {taskinstance.py:349} INFO - ::group::Post task execution logs
[2025-09-23T21:52:13.798-0300] {taskinstance.py:361} INFO - Marking task as SUCCESS. dag_id=WorkOrders, task_id=run_main, run_id=scheduled__2025-09-23T11:00:00+00:00, execution_date=20250923T110000, start_date=20250924T005209, end_date=20250924T005213
[2025-09-23T21:52:13.864-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-09-23T21:52:13.879-0300] {taskinstance.py:3924} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-23T21:52:13.896-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
