[2025-09-23T21:42:21.969-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-23T21:42:21.986-0300] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: WorkOrders.run_main manual__2025-09-24T00:42:19.549400+00:00 [queued]>
[2025-09-23T21:42:21.992-0300] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: WorkOrders.run_main manual__2025-09-24T00:42:19.549400+00:00 [queued]>
[2025-09-23T21:42:21.993-0300] {taskinstance.py:2884} INFO - Starting attempt 1 of 1
[2025-09-23T21:42:22.017-0300] {taskinstance.py:2907} INFO - Executing <Task(_PythonDecoratedOperator): run_main> on 2025-09-24 00:42:19.549400+00:00
[2025-09-23T21:42:22.027-0300] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=79) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-23T21:42:22.029-0300] {standard_task_runner.py:72} INFO - Started process 81 to run task
[2025-09-23T21:42:22.029-0300] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'WorkOrders', 'run_main', 'manual__2025-09-24T00:42:19.549400+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/Example.py', '--cfg-path', '/tmp/tmpdni1s23x']
[2025-09-23T21:42:22.031-0300] {standard_task_runner.py:105} INFO - Job 9: Subtask run_main
[2025-09-23T21:42:22.087-0300] {task_command.py:467} INFO - Running <TaskInstance: WorkOrders.run_main manual__2025-09-24T00:42:19.549400+00:00 [running]> on host 41dd0c7ecc28
[2025-09-23T21:42:22.169-0300] {taskinstance.py:3157} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='WorkOrders' AIRFLOW_CTX_TASK_ID='run_main' AIRFLOW_CTX_EXECUTION_DATE='2025-09-24T00:42:19.549400+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-24T00:42:19.549400+00:00'
[2025-09-23T21:42:22.170-0300] {taskinstance.py:740} INFO - ::endgroup::
[2025-09-23T21:42:26.995-0300] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2025-09-23T21:42:28.482-0300] {logging_mixin.py:190} INFO - 0 novas linhas para inserir.
[2025-09-23T21:42:28.483-0300] {logging_mixin.py:190} INFO - Nada a inserir. Encerrando.
[2025-09-23T21:42:28.483-0300] {python.py:240} INFO - Done. Returned value was: None
[2025-09-23T21:42:28.494-0300] {taskinstance.py:349} INFO - ::group::Post task execution logs
[2025-09-23T21:42:28.495-0300] {taskinstance.py:361} INFO - Marking task as SUCCESS. dag_id=WorkOrders, task_id=run_main, run_id=manual__2025-09-24T00:42:19.549400+00:00, execution_date=20250924T004219, start_date=20250924T004221, end_date=20250924T004228
[2025-09-23T21:42:28.550-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-09-23T21:42:28.563-0300] {taskinstance.py:3924} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-23T21:42:28.565-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
